package config

import (
	"flag"
	"log/slog"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	"github.com/labring/devbox-sdk-server/pkg/utils"
)

type Config struct {
	Addr               string
	LogLevel           slog.Level
	WorkspacePath      string
	MaxFileSize        int64
	Token              string
	TokenAutoGenerated bool
}

func getLogLevel(logLevel string) slog.Level {
	switch strings.ToUpper(logLevel) {
	case "DEBUG":
		return slog.LevelDebug
	case "WARN", "WARNING":
		return slog.LevelWarn
	case "ERROR":
		return slog.LevelError
	default:
		return slog.LevelInfo
	}
}

// ParseCfg parses configuration from environment variables and command-line flags.
func ParseCfg() *Config {
	cfg := &Config{
		Addr:          ":9757",
		LogLevel:      slog.LevelInfo,
		WorkspacePath: "/workspace",
		MaxFileSize:   100 * 1024 * 1024, // 100MB
	}

	// Read environment variables
	addrEnv := os.Getenv("ADDR")
	logLevelEnv := os.Getenv("LOG_LEVEL")
	workspacePathEnv := os.Getenv("WORKSPACE_PATH")
	maxFileSizeEnv := os.Getenv("MAX_FILE_SIZE")
	tokenEnv := os.Getenv("TOKEN")

	addrFlag := flag.String("addr", cfg.Addr, "server addr")
	logLevelFlag := flag.String("log_level", slog.LevelInfo.String(), "log level (DEBUG|INFO|WARN|ERROR)")
	workspacePathFlag := flag.String("workspace_path", cfg.WorkspacePath, "workspace path")
	maxFileSizeFlag := flag.String("max_file_size", strconv.FormatInt(cfg.MaxFileSize, 10), "max file size in bytes")
	tokenFlag := flag.String("token", "", "auth token for API requests")
	flag.Parse()

	// Priority: command-line flags > environment variables > defaults
	if *addrFlag != "" {
		cfg.Addr = *addrFlag
	} else if addrEnv != "" {
		cfg.Addr = addrEnv
	}

	if *logLevelFlag != "" {
		cfg.LogLevel = getLogLevel(*logLevelFlag)
	} else if logLevelEnv != "" {
		cfg.LogLevel = getLogLevel(logLevelEnv)
	}

	if *workspacePathFlag != "" {
		cfg.WorkspacePath = *workspacePathFlag
	} else if workspacePathEnv != "" {
		cfg.WorkspacePath = workspacePathEnv
	}

	// Convert to absolute path
	workspacePath, err := filepath.Abs(cfg.WorkspacePath)
	if err != nil {
		panic("failed to resolve absolute path for workspace: " + err.Error())
	}
	cfg.WorkspacePath = workspacePath

	if *maxFileSizeFlag != "" {
		if size, err := strconv.ParseInt(*maxFileSizeFlag, 10, 64); err == nil {
			cfg.MaxFileSize = size
		}
	} else if maxFileSizeEnv != "" {
		if size, err := strconv.ParseInt(maxFileSizeEnv, 10, 64); err == nil {
			cfg.MaxFileSize = size
		}
	}

	// Token: use provided value or auto-generate
	if *tokenFlag != "" {
		cfg.Token = *tokenFlag
	} else if tokenEnv != "" {
		cfg.Token = tokenEnv
	} else {
		cfg.Token = utils.NewNanoID()
		cfg.TokenAutoGenerated = true
	}

	return cfg
}
